export { GovernmentService, getGovernmentService } from "./application/services/government.service";
export {
  DASHBOARD_LEVEL_META,
  INVESTIGATION_TYPE_META,
  INVESTIGATION_STATUS_META,
  INVESTIGATION_STEP_META,
  INSPECTION_TYPE_META,
  INSPECTION_STATUS_META,
  COMPLIANCE_LEVEL_META,
  FINDING_TYPE_META,
  CASE_TYPE_META,
  CASE_STATUS_META,
  CASE_EVENT_META,
  PRIORITY_META,
  RECOMMENDED_ACTION_META,
  GHANA_REGIONS,
  GHANA_DISTRICTS,
  computeSlaStatus,
  computeComplianceScore,
  aggregateDashboardMetrics,
} from "./domain/government-types";
export type {
  DashboardLevel,
  InvestigationType,
  InvestigationStatus,
  InvestigationStepType,
  InspectionType,
  InspectionStatus,
  ComplianceLevel,
  FindingType,
  CaseType,
  CaseStatus,
  CaseEventType,
  Priority,
  RecommendedAction,
} from "./domain/government-types";
