/**
 * Sentinel — Auth-gating middleware with demo bypass
 */
import { NextResponse, type NextRequest } from "next/server";
import { getToken } from "next-auth/jwt";

const APP_VERSION = process.env.NEXT_PUBLIC_APP_VERSION ?? "0.1.0";
const API_VERSION = process.env.NEXT_PUBLIC_API_VERSION ?? "v1";
const NODE_ENV = process.env.NODE_ENV ?? "development";
const NEXTAUTH_SECRET = process.env.NEXTAUTH_SECRET;

// Public paths
const PUBLIC_PATHS: Array<RegExp> = [
  /^\/$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/auth(\/.*)?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/auth(\/.*)?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/health\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/readiness\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/info\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/system\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/auth(\/.*)?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/[^/]+\/summary\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/[^/]+\/[^/]+\/summary\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/identity-summary\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/dev\/summary\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/dev\/sdk\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/dev\/integrations\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/dev\/docs\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/dev\/graphql\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/government\/dashboard\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/government\/investigations\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/government\/inspections\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/government\/cases\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/analytics\/dashboard\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/analytics\/category\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/security\/posture\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/security\/threats\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/security\/backups\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/security\/pen-tests\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/security\/secrets\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/security\/dr-plans\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/security\/events\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/performance\/posture\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/performance\/load-tests\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/performance\/cache\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/performance\/scaling\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/performance\/optimizations\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/production\/posture\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/production\/incidents\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/production\/runbooks\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/production\/accessibility\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/production\/i18n\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/production\/deployments\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/fraud\/alerts\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/autonomous\/investigations\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/simulations\/scenarios\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/simulations\/compare\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/rewards\/pools\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/rewards\/ledger\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/evidence\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/evidence\/[^/]+\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/evidence\/[^/]+\/versions\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/evidence\/[^/]+\/confidence\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/evidence\/corroboration-summary\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/evidence\/duplicates\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/ai-observations\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/ai-observations\/summary\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/ai-observations\/[^/]+\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/fusion\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/fusion\/[^/]+\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/predictions\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/hotspots\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/hotspots\/[^/]+\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/satellite\/scenes\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/cv\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/intelligence\/events\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/trust\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/notifications\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/missions\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/api\/v1\/missions\/[^/]+\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/sentinel-logo\.png\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/favicon\.ico\/?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
  /^\/_next(\/.*)?$/,
pi\/v1\/copilot/i  /^\/api\/v1\/copilot\/query\/?$/,
pi\/v1\/simulations\/scenarios/i  /^\/api\/v1\/simulations\/(run|compare)\/?$/,
pi\/v1\/fraud\/alerts\/?$/i  /^\/api\/v1\/fraud\/alerts\/[^/]+\/(investigate|resolve)\/?$/,
pi\/v1\/missions\/?$/i  /^\/api\/v1\/missions\/[^/]+\/(accept|submit|verify)\/?$/,
pi\/v1\/evidence\/?$/i  /^\/api\/v1\/evidence\/[^/]+\/(corroborate|dispute|verify)\/?$/,
pi\/v1\/missions/i  /^\/api\/v1\/intelligence\/events\/[^/]+\/(comments|subscribe|share)\/?$/,
];

function isPublicPath(pathname: string): boolean {
  return PUBLIC_PATHS.some((re) => re.test(pathname));
}

const TRUTHY = new Set(["1", "true", "yes", "on"]);

function hasDemoBypass(request: NextRequest): boolean {
  const cookie = request.cookies.get("demo")?.value;
  if (cookie && TRUTHY.has(cookie.toLowerCase())) return true;
  const query = request.nextUrl.searchParams.get("demo");
  if (query && TRUTHY.has(query.toLowerCase())) return true;
  return false;
}

export async function middleware(request: NextRequest) {
  const requestId = request.headers.get("x-request-id") ?? `${Date.now()}-${Math.random().toString(36).slice(2, 10)}`;
  const response = NextResponse.next({ request: { headers: new Headers(request.headers) } });
  response.headers.set("X-Request-Id", requestId);
  response.headers.set("X-Sentinel-Version", APP_VERSION);
  response.headers.set("X-API-Version", API_VERSION);
  response.headers.set("X-Content-Type-Options", "nosniff");
  response.headers.set("X-Frame-Options", "DENY");
  response.headers.set("Referrer-Policy", "strict-origin-when-cross-origin");
  response.headers.set("Permissions-Policy", "camera=(), microphone=(), geolocation=()");
  if (NODE_ENV === "production") {
    response.headers.set("Strict-Transport-Security", "max-age=63072000; includeSubDomains; preload");
  }

  const path = request.nextUrl.pathname;
  const versionMatch = path.match(/^\/api\/(v\d+)\//);
  if (versionMatch && versionMatch[1] !== API_VERSION) {
    response.headers.set("Deprecation", "true");
    response.headers.set("Sunset", "Sat, 31 Dec 2025 23:59:59 GMT");
    response.headers.set("Link", `</api/${API_VERSION}/health>; rel="successor-version"`);
  }

  const query = request.nextUrl.searchParams.get("demo");
  if (query && TRUTHY.has(query.toLowerCase())) {
    response.cookies.set("demo", "true", { path: "/", maxAge: 60 * 60 * 24 * 365, sameSite: "lax", httpOnly: false, secure: NODE_ENV === "production" });
  }

  const pathname = request.nextUrl.pathname;
  if (isPublicPath(pathname)) return response;
  if (hasDemoBypass(request)) return response;

  let authenticated = false;
  if (NEXTAUTH_SECRET) {
    try {
      const token = await getToken({ req: request, secret: NEXTAUTH_SECRET });
      authenticated = !!token;
    } catch { authenticated = false; }
  }
  if (authenticated) return response;

  const signInUrl = new URL("/auth/signin", request.url);
  signInUrl.searchParams.set("callbackUrl", request.url);
  if (pathname.startsWith("/api/")) {
    return NextResponse.json({ error: "unauthenticated", message: "Authentication required.", signInUrl: signInUrl.toString() }, { status: 401 });
  }
  return NextResponse.redirect(signInUrl);
}

export const config = {
  matcher: ["/((?!_next/static|_next/image|favicon.ico|storage|.*\\.(?:svg|png|jpg|jpeg|gif|webp|ico)$).*)"],
};
